### ISSUE TITLE
I tried using it on linux mint 20 and it didn't work (no error message or anything)

### ISSUE THREAD

**Issue by perospirone** [vbe0201/vimdiscord#4]

**Comment by J0sueTM** [comment]
it also don't work on arch linux. I tried changing terminal, reinstalling, re-login on discord, try the terminal based, but still nothing. I think it was made for windows, but I'm not sure.

Edit: I'm now on pop os and it still don't work

**Comment by TheGreatMcPain** [comment]
I had to edit the `PIPE_PATH` variable inside `plugin/rpc.py`

For some reason it uses the path `/run/user/"your user id"/snap.discord/discord-ipc-0` by default. Which is fine for the snap version of Discord, but the version I have puts the `discord-ipc-0` file in `/run/user/1000`.

I got rid of the `snap.discord/` part of `PIPE_PATH` and it works now.

Here's what my `PIPE_PATH` looks like.

```
PIPE_PATH = R'\\?\pipe\discord-ipc-{}' if ON_WINDOWS else R'discord-ipc-{}'
```

**Comment by J0sueTM** [comment]
Thank you so much. It works now.

**Comment by AlexandrosVasileiou** [comment]
Still not working for me even after trying what's mentioned in the comments above.
Do you have any clue on how to make this work on Arch? Discord is installed via the AUR and it's located in /opt/discord
I tried editing the above path according to where discord is located but with no luck.

Any clues?

**Comment by AlexandrosVasileiou** [comment]
My bad. I had "Game Activity" off from the user settings of Discord :man_facepalming:
