### ISSUE TITLE
Sometimes doesnt work with discord-canary (arch linux)

### ISSUE THREAD

**Issue by gdnathan** [vbe0201/vimdiscord#6]
sometimes it work, but most of the time, it does not. No error message, nothing

Im using discord-canary (`discord-canary` package), on Arch linux. any hints?

**Comment by felipejoribeiro** [comment]
I'm using arch too and the plugin seems to not work here too. I'm using discord 0.0.15-1 package from pacman.

(EDIT):
Just found the solution in the other issue. Here it is:

https://github.com/vbe0201/vimdiscord/issues/4#issuecomment-708872623
